FROM amazeeio/php:7.1-cli
COPY .lagoon/php-worker.ini /usr/local/etc/php/php.ini
COPY composer.json composer.lock /app/
RUN composer install --no-dev --prefer-dist

RUN docker-php-ext-install pcntl 

ENV APP_ENV=${LAGOON_ENVIRONMENT_TYPE}
ENV WEBROOT=public
ENV PAGER=less
ENV PHP_MEMORY_LIMIT=8192M
CMD ["/app/scripts/worker.sh"]
