FROM amazeeio/php:7.1-cli

COPY lagoon/php-cli.ini /usr/local/etc/php/php.ini
COPY composer.json composer.lock /app/
RUN composer install --no-dev --prefer-dist

COPY . /app
ENV WEBROOT=public
ENV PAGER=less
